import { Outfit } from "next/font/google";
import "./globals.css";
import Header from "@/components/share/Header/Header";
import Footer from "@/components/share/Footer/Footer";
import NavBar from "@/components/share/Header/NavBar";
import { Storeprovider } from "./Provider/Provider";

const font = Outfit({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin']
});



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Storeprovider >
        <body
          className={`${font.className} antialiased `}
        >
          <Header />
          <NavBar />
          {children}
          <Footer />
        </body>
      </Storeprovider>
    </html>
  );
}
